version: "3.7"

volumes:
  uploads_data:

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - tenpaws-server

  tenpaws-server:
    image: 533267244952.dkr.ecr.ap-northeast-2.amazonaws.com/tenpaws-server:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://RDS_ENDPOINT_PLACEHOLDER:3306/tenpaws?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: MYSQL_USERNAME_PLACEHOLDER
      SPRING_DATASOURCE_PASSWORD: MYSQL_PASSWORD_PLACEHOLDER
    volumes:
      - uploads_data:/home/ubuntu/tenpaws-server/uploads  # 업로드 디렉토리 마운트
    entrypoint: >
     /bin/sh -c "java -jar project.jar --spring.config.location=file:/home/ubuntu/tenpaws-server/src/main/resources/application.properties"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"